name: tekartik_http_node
description: Http node
version: 0.6.0
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  tekartik_http:
    git:
      url: https://github.com/tekartik/http.dart
      path: http
    version: '>=0.6.0'
  tekartik_http_io:
    git:
      url: https://github.com/tekartik/http.dart
      path: http_io
    version: '>=0.6.0'
  tekartik_core_node:
    git:
      url: https://github.com/tekartik/common_node.dart
      path: core_node
  http:
  fetch_client:
  # node_interop: ">=1.0.3"
  # node_io: '>=1.0.1+2'
  # node_http: '>=1.0.0'
  meta: ">=1.15.0"
  tekartik_fs_node:
    git:
      url: https://github.com/tekartik/common_node.dart
      path: fs_node
    version: '>=0.1.0'
  tekartik_common_utils:
    git: https://github.com/tekartik/common_utils.dart

dev_dependencies:
  test: ">=1.24.0"
  build_runner: ">=2.4.13"
  build_test: '>=0.10.8'
  # build_node_compilers: ">=0.2.2"
  tekartik_platform_node:
    git:
      url: https://github.com/tekartik/common_node.dart
      path: platform_node
    version: '>=0.1.0'

  tekartik_http_test:
    git:
      url: https://github.com/tekartik/http.dart
      path: http_test
    version: '>=0.1.0'

resolution: workspace
